include $(PROJECT_PATH)/common.mk

ARDUINO_LIBRARIES := SparkFun_APDS9960

NODE_HOSTNAME=\"gesture_sensor\"
COMPONENT_CFLAGS += -DNODE_HOSTNAME=$(NODE_HOSTNAME)

SMING_ARCH = Esp8266
SPI_MODE = qio
SPI_SIZE = 4M
COM_SPEED_ESPTOOL = 1500000
COM_PORT = /dev/ttyUSB0
COM_OPTS = --raw
COM_SPEED = 1500000
COM_SPEED_ESPTOOL = $(COM_SPEED)
COM_SPEED_SERIAL = $(COM_SPEED)
